[global]
excludes = [
  "nix/*"
]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh", "bin/*", ".envrc"]
options = [
  "-i",
  "2",  # indent 2
  "-s", # simplify the code
  "-w", # write back to the file
]
