require('pwm.settings')
require('pwm.telescope')
require('pwm.treesitter')
require('pwm.neotree')
require('pwm.neogit')
require('pwm.comment')
require('pwm.lualine')
require('pwm.gitsigns')
require('pwm.lsp')
-- require('pwm.cmp')
