require('config.settings')
require('config.telescope')
require('config.treesitter')
require('config.neotree')
require('config.neogit')
require('config.comment')
require('config.lualine')
require('config.gitsigns')
require('config.lsp')
-- require('config.cmp')
